# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getBarrierUpandInPutPrice <- function(b, nInt, strike, spot, vol, r, expiry, nReps) {
    .Call(`_myoptionPricer2_getBarrierUpandInPutPrice`, b, nInt, strike, spot, vol, r, expiry, nReps)
}

rcpp_hello_world <- function() {
    .Call(`_myoptionPricer2_rcpp_hello_world`)
}

